### ISSUE TITLE
error of U-Plane1

### ISSUE THREAD

**Issue by sing1020** [s5uishida/free5gc_ueransim_sample_config#3]
Hi, @s5uishida 
I tried to create the One SMF, Multiple UPFs and DNNs of your Sample Configurations and followed the steps.
When I tried to run the free5GC U-Plan1, I got the error.
![image](https://user-images.githubusercontent.com/111422226/198920596-fe2edd2e-41e4-4518-90d5-2f7e0cfb6196.png)

Have you ever had the same problem? 
Any suggestions or helps are appreciated:)

Linux version: ubuntu-20.04.5-live-server-amd64
free5GC version: v3.2.1

Thanks.

Best Regards
Hsin

**Comment by s5uishida** [comment]
Hi @sing1020 

In my environment, it works as follows.
```
root@free5gc12:~/free5gc# bin/upf 
2022-10-31T13:01:33+09:00 [INFO][UPF][Main] UPF version:  
        free5GC version: v3.2.1-13-ge104d46
        build time:      2022-10-17T01:23:52Z
        commit hash:     e05c3433
        commit time:     2022-09-02T01:58:48Z
        go version:      go1.14.4 linux/amd64
2022-10-31T13:01:33+09:00 [INFO][UPF][Cfg] Read config from [./config/upfcfg.yaml]
2022-10-31T13:01:33+09:00 [INFO][UPF][Cfg] ==================================================
2022-10-31T13:01:33+09:00 [INFO][UPF][Cfg] (*factory.Config)(0xc000342780)({
        Version: (string) (len=5) "1.0.3",
        Description: (string) (len=31) "UPF initial local configuration",
        Pfcp: (*factory.Pfcp)(0xc000354fc0)({
                Addr: (string) (len=14) "192.168.66.142",
                NodeID: (string) (len=14) "192.168.66.142",
                RetransTimeout: (time.Duration) 1s,
                MaxRetrans: (uint8) 3
        }),
        Gtpu: (*factory.Gtpu)(0xc000355170)({
                Forwarder: (string) (len=5) "gtp5g",
                IfList: ([]factory.IfInfo) (len=1 cap=1) {
                        (factory.IfInfo) {
                                Addr: (string) (len=14) "192.168.66.142",
                                Type: (string) (len=2) "N3",
                                Name: (string) "",
                                IfName: (string) "",
                                MTU: (uint32) 0
                        }
                }
        }),
        DnnList: ([]factory.DnnList) (len=2 cap=2) {
                (factory.DnnList) {
                        Dnn: (string) (len=8) "internet",
                        Cidr: (string) (len=12) "10.60.0.0/16",
                        NatIfName: (string) ""
                },
                (factory.DnnList) {
                        Dnn: (string) (len=9) "internet2",
                        Cidr: (string) (len=12) "10.61.0.0/16",
                        NatIfName: (string) ""
                }
        },
        Logger: (*factory.Logger)(0xc0002dfac0)({
                Enable: (bool) true,
                Level: (string) (len=4) "info",
                ReportCaller: (bool) false
        })
})
2022-10-31T13:01:33+09:00 [INFO][UPF][Cfg] ==================================================
2022-10-31T13:01:33+09:00 [INFO][UPF][Main] Log level is set to [info] level
2022-10-31T13:01:33+09:00 [INFO][UPF][Main] starting Gtpu Forwarder [gtp5g]
2022-10-31T13:01:33+09:00 [INFO][UPF][Main] GTP Address: "192.168.66.142:2152"
2022-10-31T13:01:33+09:00 [INFO][UPF][Buff] buff server started
2022-10-31T13:01:33+09:00 [INFO][UPF][Pfcp][192.168.66.142:8805] starting pfcp server
2022-10-31T13:01:33+09:00 [INFO][UPF][Pfcp][192.168.66.142:8805] pfcp server started
2022-10-31T13:01:33+09:00 [INFO][UPF][Main] UPF started
```

**Comment by sing1020** [comment]
Hi, @s5uishida 

Sorry I gave the worng information that my free5GC version is v3.2.0,
and I found that our go version is different.
Is it possible that error is cased by the versions not support or other reasion?
Thanks.

ubuntu@free5gc:~/free5gc$ sudo ./bin/upf
2022-10-31T06:19:13Z [INFO][UPF][Main] UPF version:
        free5GC version: v3.2.0
        build time:      2022-10-13T04:05:41Z
        commit hash:     4972fffb
        commit time:     2022-06-29T05:46:33Z
        go version:      go1.19.2 linux/amd64
2022-10-31T06:19:13Z [INFO][UPF][Cfg] Read config from [./config/upfcfg.yaml]
2022-10-31T06:19:13Z [INFO][UPF][Cfg] ==================================================
2022-10-31T06:19:13Z [INFO][UPF][Cfg] (*factory.Config)(0xc000067180)({
        Version: (string) (len=5) "1.0.3",
        Description: (string) (len=31) "UPF initial local configuration",
        Pfcp: (*factory.Pfcp)(0xc0001a1f20)({
                Addr: (string) (len=14) "192.168.56.142",
                NodeID: (string) (len=14) "192.168.56.142",
                RetransTimeout: (time.Duration) 1s,
                MaxRetrans: (uint8) 3
        }),
        Gtpu: (*factory.Gtpu)(0xc0002760f0)({
                Forwarder: (string) (len=5) "gtp5g",
                IfList: ([]factory.IfInfo) (len=1 cap=1) {
                        (factory.IfInfo) {
                                Addr: (string) (len=14) "192.168.56.142",
                                Type: (string) (len=2) "N3",
                                Name: (string) "",
                                IfName: (string) ""
                        }
                }
        }),
        DnnList: ([]factory.DnnList) (len=2 cap=2) {
                (factory.DnnList) {
                        Dnn: (string) (len=8) "internet",
                        Cidr: (string) (len=12) "10.60.0.0/16",
                        NatIfName: (string) ""
                },
                (factory.DnnList) {
                        Dnn: (string) (len=9) "internet2",
                        Cidr: (string) (len=12) "10.61.0.0/16",
                        NatIfName: (string) ""
                }
        },
        Logger: (*factory.Logger)(0xc0001fc740)({
                Enable: (bool) true,
                Level: (string) (len=4) "info",
                ReportCaller: (bool) false
        })
})
2022-10-31T06:19:13Z [INFO][UPF][Cfg] ==================================================
2022-10-31T06:19:13Z [INFO][UPF][Main] Log level is set to [info] level
2022-10-31T06:19:13Z [INFO][UPF][Main] starting Gtpu Forwarder [gtp5g]
2022-10-31T06:19:13Z [INFO][UPF][Main] GTP Address: "192.168.56.142:2152"
2022-10-31T06:19:13Z [ERRO][UPF][Main] UPF Cli Run Error: open Gtp5g: open link: create: operation not supported
ubuntu@free5gc:~/free5gc$

**Comment by s5uishida** [comment]
Hi @sing1020 

I was able to get the latest versions of free5GC and gtp5g installed and working by following the steps below.

https://github.com/free5gc/free5gc/wiki/Installation

For earlier versions, I think it probably works, but I'm not sure.

**Comment by sing1020** [comment]
Hi @s5uishida 

OK, I'll try it.
If it works due to the different versions, I would let you know:)

Thanks.

**Comment by sing1020** [comment]
Hi @s5uishida 

It works in my environment.
![image](https://user-images.githubusercontent.com/111422226/198963802-67490af2-52af-414f-a332-2ba8cc971468.png)

And I found the reason for the error is that I stupidly gave the wrong IP address of the DNN...
I'm going to create rest of it, thanks.

**Comment by s5uishida** [comment]
Hi @sing1020 

I don't understand why you set the CIDR as that way for DNN=internet and internet2.

For your reference, my `upfcfg.yaml` is as follows.

`~/free5gc/config/upfcfg.yaml`
```
version: 1.0.3
description: UPF initial local configuration

# The listen IP and nodeID of the N4 interface on this UPF (Can't set to 0.0.0.0)
pfcp:
  addr: 192.168.66.142   # IP addr for listening
  nodeID: 192.168.66.142 # External IP or FQDN can be reached
  retransTimeout: 1s # retransmission timeout
  maxRetrans: 3 # the max number of retransmission

gtpu:
  forwarder: gtp5g
  # The IP list of the N3/N9 interfaces on this UPF
  # If there are multiple connection, set addr to 0.0.0.0 or list all the addresses
  ifList:
    - addr: 192.168.66.142
      type: N3
      # name: upf.5gc.nctu.me
      # ifname: gtpif

# The DNN list supported by UPF
dnnList:
  - dnn: internet # Data Network Name
    cidr: 10.60.0.0/16 # Classless Inter-Domain Routing for assigned IPv4 pool of UE
    # natifname: eth0
  - dnn: internet2
    cidr: 10.61.0.0/16

logger: # log output setting
  enable: true # true or false
  level: info # how detailed to output, value: trace, debug, info, warn, error, fatal, panic
  reportCaller: false # enable the caller report or not, value: true or false
```
